/* Bundles the whole simulation into one self-contained HTML file.
   Usage: node build.mjs   →   dist/veritas-simulation.html
   The result has no external requests at all: open it by double-clicking,
   email it, or upload it to an LMS as a single attachment. */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const read = f => fs.readFileSync(path.join(ROOT, f), "utf8");

let html = read("index.html");

// Inline the stylesheet
// Replacements use a function, not a string: the sources contain "$&" (in a
// regex-escape call) which a string replacement would expand as a pattern.
html = html.replace(
  '<link rel="stylesheet" href="styles.css">',
  () => `<style>\n${read("styles.css")}\n</style>`
);

// Inline the scripts, in order, as one block
const scripts = ["js/content.js", "js/badges.js", "js/llm.js", "js/app.js"];
const bundled = scripts.map(f => `/* ===== ${f} ===== */\n${read(f)}`).join("\n\n");

// A literal </script> inside JS would close the tag early. None today; guard anyway.
if (/<\/script/i.test(bundled)) throw new Error("Source contains </script> — escape it before bundling.");

html = html.replace(
  scripts.map(f => `<script src="${f}"></script>`).join("\n"),
  () => `<script>\n${bundled}\n</script>`
);

// Note for anyone who opens the file in an editor
html = html.replace("</head>",
  () => `<!-- Single-file build. Generated by build.mjs from the source folder;\n     edit the sources, not this file. -->\n</head>`);

fs.mkdirSync(path.join(ROOT, "dist"), { recursive: true });
const out = path.join(ROOT, "dist", "veritas-simulation.html");
fs.writeFileSync(out, html);
console.log(`Wrote ${path.relative(ROOT, out)} — ${(html.length / 1024).toFixed(0)} KB`);
